version: '3.8'
 
services:
  api:
    build:
      context: ./api
    ports:
      - "8080:80"
    depends_on:
      - mysql
 
  mysql:
    build:
      context: ./mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: instagram-clone
      MYSQL_USER: root
      MYSQL_PASSWORD: 
 
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"  # Adjust the port as needed
    depends_on:
      - api